# Loops


    FOR loop
    While loop


In [1]:
simple_list=[0,1,2,3,4,5,45,786]
print(simple_list)

[0, 1, 2, 3, 4, 5, 45, 786]


In [2]:
for i in simple_list:
    print(i)

0
1
2
3
4
5
45
786


In [5]:
for i in simple_list[1:5]:
    for j in simple_list[4:8]:
        print(i*j)

4
5
45
786
8
10
90
1572
12
15
135
2358
16
20
180
3144


In [6]:
# looping over a range of values
print(range(6))

range(0, 6)


In [8]:
for i in range (6):
    print(i)

0
1
2
3
4
5


In [9]:
for i in range(5,10):
    print(i)


5
6
7
8
9


In [10]:
for i in range(4,20,2):
    print(i)

4
6
8
10
12
14
16
18


In [3]:
#Printing square from 1 to 10 using a for loop

In [13]:
for i in range(1,11):
    print(i*i)

1
4
9
16
25
36
49
64
81
100


In [14]:
x=[1,2,3,4,5,6,7,8,9,10]
for i in x:
    print('square of {} is {}'.format(i,i*i))

square of 1 is 1
square of 2 is 4
square of 3 is 9
square of 4 is 16
square of 5 is 25
square of 6 is 36
square of 7 is 49
square of 8 is 64
square of 9 is 81
square of 10 is 100


In [1]:
x=range(11)
for i in x:
    print(f'square of {i} is {i*i}')

square of 0 is 0
square of 1 is 1
square of 2 is 4
square of 3 is 9
square of 4 is 16
square of 5 is 25
square of 6 is 36
square of 7 is 49
square of 8 is 64
square of 9 is 81
square of 10 is 100


### Using IF-ELSE with for Loop

In [2]:
#Printing squares of even numbers from 1 to 100
x=range(101)
for i in x:
    if i%2==0:
        print(f'square of {i} is {i*i}')

square of 0 is 0
square of 2 is 4
square of 4 is 16
square of 6 is 36
square of 8 is 64
square of 10 is 100
square of 12 is 144
square of 14 is 196
square of 16 is 256
square of 18 is 324
square of 20 is 400
square of 22 is 484
square of 24 is 576
square of 26 is 676
square of 28 is 784
square of 30 is 900
square of 32 is 1024
square of 34 is 1156
square of 36 is 1296
square of 38 is 1444
square of 40 is 1600
square of 42 is 1764
square of 44 is 1936
square of 46 is 2116
square of 48 is 2304
square of 50 is 2500
square of 52 is 2704
square of 54 is 2916
square of 56 is 3136
square of 58 is 3364
square of 60 is 3600
square of 62 is 3844
square of 64 is 4096
square of 66 is 4356
square of 68 is 4624
square of 70 is 4900
square of 72 is 5184
square of 74 is 5476
square of 76 is 5776
square of 78 is 6084
square of 80 is 6400
square of 82 is 6724
square of 84 is 7056
square of 86 is 7396
square of 88 is 7744
square of 90 is 8100
square of 92 is 8464
square of 94 is 8836
square of 96 is 9216

In [3]:
# odd number
x=range(101)
for i in x:
    if i%2==1:
        print(f'square of {i} is {i*i}')

square of 1 is 1
square of 3 is 9
square of 5 is 25
square of 7 is 49
square of 9 is 81
square of 11 is 121
square of 13 is 169
square of 15 is 225
square of 17 is 289
square of 19 is 361
square of 21 is 441
square of 23 is 529
square of 25 is 625
square of 27 is 729
square of 29 is 841
square of 31 is 961
square of 33 is 1089
square of 35 is 1225
square of 37 is 1369
square of 39 is 1521
square of 41 is 1681
square of 43 is 1849
square of 45 is 2025
square of 47 is 2209
square of 49 is 2401
square of 51 is 2601
square of 53 is 2809
square of 55 is 3025
square of 57 is 3249
square of 59 is 3481
square of 61 is 3721
square of 63 is 3969
square of 65 is 4225
square of 67 is 4489
square of 69 is 4761
square of 71 is 5041
square of 73 is 5329
square of 75 is 5625
square of 77 is 5929
square of 79 is 6241
square of 81 is 6561
square of 83 is 6889
square of 85 is 7225
square of 87 is 7569
square of 89 is 7921
square of 91 is 8281
square of 93 is 8649
square of 95 is 9025
square of 97 is 9409

## While Loop

In [20]:
i=5
while i<10:
    print(i)
    i=i+1

5
6
7
8
9


In [22]:
#Printing square from 1 to 10
i=0
while i<=10:
    print(f'square of {i} is {i*i}')
    i=i+1

square of 0 is 0
square of 1 is 1
square of 2 is 4
square of 3 is 9
square of 4 is 16
square of 5 is 25
square of 6 is 36
square of 7 is 49
square of 8 is 64
square of 9 is 81
square of 10 is 100


In [27]:
i=0
while i<=10:
    if i%2==0:
        print(f'square of {i} is {i*i}')
    i=i+1

square of 0 is 0
square of 2 is 4
square of 4 is 16
square of 6 is 36
square of 8 is 64
square of 10 is 100


### Using IF-ELSE with `while` Loop

In [7]:
# while loop for access permission
while True:
    user_id=input('Enter user name')
    password=int(input('Enter password'))
    if user_id=='abcd' and password==1234:
        print('Login Sucess')
    else:
        print('Login Failure')

KeyboardInterrupt: Interrupted by user

In [8]:
user_id=input('Enter user name')
password=int(input('Enter password'))
if user_id=='abcd' and password==1234:
    print('Login Sucess')
else:
    print('Login Failure')

KeyboardInterrupt: Interrupted by user

## You gotta use your python skills to help your local shopkeeper calculate the Net Price for his shop's product provided below along with it's respective GST slab

GST Amount = ( Original Cost * GST ) / 100

Net Price = Original Cost + GST Amount

Product Cost / GST Slab

Product1- 1000 / 18%

Product2- 250 / 18%

Product3- 125 / 5%

Product4- 345 / 18%

Product5- 820 / 12%

Product6- 980 / 5%

Product7- 500 / 12%

In [4]:
# Hint Create a dictionary and loop

In [31]:
product_gst_slab={'Product1':18,'Product2':18,'Product3':5,'Product4':18,'Product5':12,'Product6':5,'Product7':12}
product_original_cost={'Product1':1000,'Product2':250,'Product3':125,'Product4':345,'Product5':820,'Product6':980,'Product7':500}

In [32]:
product_gst_slab.keys()

dict_keys(['Product1', 'Product2', 'Product3', 'Product4', 'Product5', 'Product6', 'Product7'])

In [34]:
for i in product_gst_slab.keys():
    gst_amount=(product_original_cost[i]*product_gst_slab[i])/100
    Net_price=(product_original_cost[i]+gst_amount)
    print('The Net Price of {} at gst{} is {}'.format(i,product_gst_slab[i],Net_price))

The Net Price of Product1 at gst18 is 1180.0
The Net Price of Product2 at gst18 is 295.0
The Net Price of Product3 at gst5 is 131.25
The Net Price of Product4 at gst18 is 407.1
The Net Price of Product5 at gst12 is 918.4
The Net Price of Product6 at gst5 is 1029.0
The Net Price of Product7 at gst12 is 560.0


# User defined functions

In [ ]:
# # define a function that takes an input, squares it, adds 7, then returns the answer

In [35]:
def x2p7(x):
    y=x*x
    z=y+7
    return(z)

In [36]:
x2p7(7)

56

In [ ]:
# Write a function to add and subtract two variables

In [37]:
def math_fun(x,y):
    add=x+y
    sub=x-y
    return(add,sub)

In [38]:
math_fun(6,4)

(10, 2)

In [40]:
def evenodd(x):
    if x%2==0:
        print("Even Number")
    else:
        print("Odd Number")
evenodd(65)

Odd Number


In [6]:
### Write a UDF that returns true if the input is a prime number and False otherwise.

In [41]:
def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

In [44]:
is_prime(37)

True

In [43]:
is_prime(12)

False

In [62]:
def prime(x):
    if (x==1):
        return False
    elif (x==2):
        return True
    else:
        for n in range(2,x):
            if (x%n==0):
                return False
    return True
prime(21)

False

In [56]:
def is_prime(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True


In [63]:
is_prime(21)

False

In [7]:
### Write a UDF that takes a list as input and returns the reverse list.

In [64]:
def Reversing(listing):
    listing.reverse()
    return lst

In [66]:
lst=[45,87,23,12,8,657]

In [67]:
Reversing(lst)

[657, 8, 12, 23, 87, 45]

In [68]:
# lambda function
lamx2p7=lambda x: x*x+7
print(lamx2p7(3))

16


In [69]:
lam1=lambda x,y,z: x*y+y*z+y/z
print(lam1(3,6,12))

90.5


# ARRAY

In [1]:
#Create an Array

import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#0-dimensional array

arr=np.array(23)
print(arr)

23


In [5]:
#1-D array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.shape

(4,)

In [8]:
arr.ndim

1

In [9]:
#2-D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr.shape

(2, 4)

In [11]:
arr.ndim

2

In [12]:
#3-D array
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [13]:
arr.shape

(2, 2, 4)

In [15]:
arr.ndim

3

In [14]:
arr.size

16

In [16]:
#Multi dimensional array
my_array=np.array([1,2,3,4],ndmin=5)
print(my_array)

[[[[[1 2 3 4]]]]]


In [17]:
my_array.ndim

5

In [18]:
zeros=np.zeros((5))

In [19]:
zeros

array([0., 0., 0., 0., 0.])

In [21]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros=np.zeros((2,5,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
arng=np.arange(15)
arng                              #it is a numpu array range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspc=np.linspace(1,5,12)

lspc

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
lspc=np.linspace(1,5,5)

lspc

array([1., 2., 3., 4., 5.])

In [26]:
emp=np.empty((1,5))

In [27]:
emp

array([[1., 2., 3., 4., 5.]])

In [28]:
emp=np.empty((4,7))

In [29]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.45593934e-307,
        7.56593017e-307],
       [1.11261027e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307, 6.23059726e-307, 1.86919513e-306,
        6.23061763e-307],
       [1.33511290e-306, 9.34608432e-307, 2.22522597e-306,
        8.90109671e-307, 2.22522597e-306, 8.90109671e-307,
        1.33512376e-306],
       [6.23054972e-307, 9.34598926e-307, 1.69118515e-306,
        9.34607074e-307, 8.90098127e-307, 7.56602523e-307,
        8.34451503e-308]])

In [30]:
emplike=np.empty_like((lspc))

In [31]:
emplike

array([1., 2., 3., 4., 5.])

In [32]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
#accessing an array
my_array=np.array([1,2,3,4])
print(my_array)

[1 2 3 4]


In [38]:
#upcasting data types
my_array=np.array([1,2,3,'4'])
print(my_array)

['1' '2' '3' '4']


In [39]:
my_array=np.array([1,2,3,4.5])
print(my_array)

[1.  2.  3.  4.5]


In [40]:
#indexing
my_array=np.array([1,2,3,4])
print(my_array[0])

1


In [41]:
my_array=np.array([1,2,3,4])
print(my_array[0:2])

[1 2]


In [42]:
#Using index in 2-D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,2])

3


In [43]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,2])

7


In [44]:
### doing some functions in 2d array


arr=np.array([[1,2,3,4],[5,6,7,8],[3,5,9,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 9, 8]])

In [45]:
arr.sum(axis=0)      #axis=0 means it will add row wise like 1+5+3=9

array([ 9, 13, 19, 20])

In [46]:
arr.sum(axis=1)      #axis=1 means it will add col wise like 1+2+3+4=10

array([10, 26, 25])

In [47]:
arr.T                ##T=TRANSPOSE means row will be col, col will be  row

array([[1, 5, 3],
       [2, 6, 5],
       [3, 7, 9],
       [4, 8, 8]])

In [48]:
arr.flat

In [52]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
3
5
9
8


In [53]:
arr.ndim

2

In [54]:
arr.size

12

In [55]:
arr.nbytes

48

In [56]:
##for 1dim

one=np.array([1,5,568,998])
one.argmax()           #it gives the index where the value is maximum

3

In [57]:
one.argmin()          #it gives the index where the value is minimum

0

In [58]:
one.argsort()         #it gives the indexes by sirting the values

array([0, 1, 2, 3], dtype=int64)

In [ ]:
## for 2dim

In [59]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 9, 8]])

In [60]:
arr.argmax()

10

In [61]:
arr.argmin()

0

In [62]:
arr.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 3, 2]], dtype=int64)

In [63]:
arr.argmax(axis=0)

array([1, 1, 2, 1], dtype=int64)

In [64]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [65]:
arr.ravel()        ##  it will straighten the array

array([1, 2, 3, 4, 5, 6, 7, 8, 3, 5, 9, 8])

In [66]:
## mathematical operation
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 9, 8]])

In [67]:
arr1=np.array([[1, 8, 3, 44],[5, 66, 7, 7],[5, 2, 6, 8]])
arr1

array([[ 1,  8,  3, 44],
       [ 5, 66,  7,  7],
       [ 5,  2,  6,  8]])

In [68]:
arr+arr1

array([[ 2, 10,  6, 48],
       [10, 72, 14, 15],
       [ 8,  7, 15, 16]])

In [69]:
arr*arr1

array([[  1,  16,   9, 176],
       [ 25, 396,  49,  56],
       [ 15,  10,  54,  64]])

In [70]:
arr-arr1

array([[  0,  -6,   0, -40],
       [  0, -60,   0,   1],
       [ -2,   3,   3,   0]])

In [71]:
arr/arr1

array([[1.        , 0.25      , 1.        , 0.09090909],
       [1.        , 0.09090909, 1.        , 1.14285714],
       [0.6       , 2.5       , 1.5       , 1.        ]])

In [72]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [1.73205081, 2.23606798, 3.        , 2.82842712]])

In [73]:
np.sqrt(arr1)

array([[1.        , 2.82842712, 1.73205081, 6.63324958],
       [2.23606798, 8.1240384 , 2.64575131, 2.64575131],
       [2.23606798, 1.41421356, 2.44948974, 2.82842712]])

In [74]:
np.where(arr>5)

(array([1, 1, 1, 2, 2], dtype=int64), array([1, 2, 3, 2, 3], dtype=int64))

In [ ]:
# Array vs List

In [75]:
my_list1=[1,2,3,4]                #we can't +,-,*,/ in list but in array
my_list2=[5,6,7,8]                #but we can add with position index in list as well as in array
print(f'LIST:{my_list1+my_list2}')

LIST:[1, 2, 3, 4, 5, 6, 7, 8]


In [76]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1+my_array2}')

ARRAY:[ 6  8 10 12]


In [77]:
my_array1=np.array([1,2,3,4])        
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1*my_array2}')

ARRAY:[ 5 12 21 32]


In [78]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1/my_array2}')

ARRAY:[0.2        0.33333333 0.42857143 0.5       ]


In [79]:
#Adding a single element
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1[1]+my_list2[1]}')

LIST:8


In [80]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1[1]+my_array2[1]}')

ARRAY:8


In [81]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1*my_list2}')

TypeError: can't multiply sequence by non-int of type 'list'

In [82]:
# Copy of array using .copy() 
my_array=np.array([1,2,3,4])
array_copy=my_array.copy()
my_array[1]=55
print(f'Original Array:{my_array}')
print(f'Copied Array:{array_copy}')

Original Array:[ 1 55  3  4]
Copied Array:[1 2 3 4]


In [83]:
#View in an array
my_array=np.array([1,2,3,4])
viewed_copy=my_array.view()
my_array[1]=55
print(f'Original Array:{my_array}')
print(f'Viewed Array:{viewed_copy}')

Original Array:[ 1 55  3  4]
Viewed Array:[ 1 55  3  4]


In [84]:
# Iterating an array
my_array=np.array([1,2,3,4])
for x in my_array:
    print(x)

1
2
3
4


In [85]:
#iterating on a 2D array
my_array1=np.array([[1,2,3,4],[5,6,7,8]])   
for x in my_array1:
    for i in x:
        print(i)

1
2
3
4
5
6
7
8


In [86]:
#Joining 2 Arrays
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(np.concatenate([my_array1,my_array2],axis=0))

[1 2 3 4 5 6 7 8]


In [87]:
# Joining 2Arrays
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate([my_array1,my_array2],axis=1))

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [88]:
#Joining using stack
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.stack([my_array1,my_array2],axis=2))

[[[ 1  9]
  [ 2 10]
  [ 3 11]
  [ 4 12]]

 [[ 5 13]
  [ 6 14]
  [ 7 15]
  [ 8 16]]]


In [89]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(np.stack([my_array1,my_array2],axis=0))

[[1 2 3 4]
 [5 6 7 8]]


In [91]:
#Spliting an array
my_array=np.array([1,2,3,4])
print(np.array_split(my_array,2))

[array([1, 2]), array([3, 4])]


In [92]:
#searching for a value in an array using where() returns an index position

my_array=np.array([1,2,3,4])
print(np.where(my_array==3))

(array([2], dtype=int64),)


In [93]:
# Sorting the array using the sort()
my_array=np.array([10,2,32,4,56,13])
print(np.sort(my_array))

[ 2  4 10 13 32 56]


In [94]:
# sorting in descending
my_array=np.array([10,2,32,4,56,13])
print(np.sort(my_array)[::-1])

[56 32 13 10  4  2]


In [95]:
# Filtering an array
my_array=np.array([10,2,32,4,56,13])
filtered_array=my_array>5

In [96]:
filtered_array

array([ True, False,  True, False,  True,  True])

In [97]:
print(my_array[filtered_array])

[10 32 56 13]


In [98]:
my_array=np.array([10,2,32,4,56,13])
my_array[my_array>5]
print(my_array.shape)

(6,)


In [99]:
# Create an array of 5*5(Generate random numbers)
np.random.rand(5,5)

array([[0.98606211, 0.39369258, 0.87648337, 0.23662793, 0.52098598],
       [0.26552952, 0.90276298, 0.72690504, 0.50645225, 0.09538792],
       [0.76290323, 0.18627729, 0.28335307, 0.06032644, 0.67771688],
       [0.2870347 , 0.99009503, 0.02279376, 0.47930961, 0.5522001 ],
       [0.80502599, 0.31067127, 0.53387875, 0.47559869, 0.87087322]])

In [100]:
n=np.random.randn(5,5)
print(n)

[[ 9.83732148e-02 -1.56110950e+00 -1.93640894e-04 -1.98796547e-01
  -1.90408120e-01]
 [-7.23899050e-01  4.16391551e-01  5.40024134e-01 -1.10311860e-01
   5.91447317e-01]
 [ 1.19953003e+00 -2.97972672e-01  8.81717671e-01 -6.00657718e-01
  -5.44508642e-01]
 [ 2.28614125e-01  2.97189940e-01 -1.65815874e+00 -7.89190952e-01
  -1.04020985e+00]
 [-4.32352134e-01 -3.62070049e-01  1.05921008e+00  2.25884959e+00
   6.42988457e-01]]


In [101]:
#checking shape
print(n.shape)

(5, 5)


In [102]:
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array1.shape)

(2, 4)


In [103]:
#Reshaping an array
my_array=np.array([1,2,3,4])
print(my_array.reshape(2,2))

[[1 2]
 [3 4]]


In [104]:
#reshaping a multidim into a single array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array.reshape(1,8))

[[1 2 3 4 5 6 7 8]]
